#!/usr/bin/env bash

sudo supervisorctl stop $1 2>&1 >/dev/null

# check if app has virtualenv, if so activate it
if [ -f "/home/vagrant/.venv/$1/bin/activate" ]
then
  echo "Python app found, activating virtualenv..."
	source /home/vagrant/.venv/$1/bin/activate
fi

# check if app has run.sh, and execute it if it does
if [ -f "/vagrant/apps/$1/run.sh" ]
then
	echo "Starting $1..."
	source /vagrant/apps/$1/run.sh
else
	echo "$1 does not have a run.sh"
fi

# check if app has torquebox.rb, if so stop torquebox and start it in foreground
if [ -f "/vagrant/apps/$1/torquebox.rb" ]
then
	sudo supervisorctl stop torquebox 2>&1 >/dev/null
	echo "Starting torquebox..."
	/home/vagrant/.rvm/bin/rvm-exec jruby-1.7.19 torquebox run -p 8888
fi
