#!/usr/bin/env bash

HOME='/home/vagrant'

# Check yo' privledge
# if [ $(id -u) != 0 ]; then
#   echo "You must be root to run $0"
#   exit 1
# fi

if [[ ! $(id vagrant) ]]; then
  echo "You must run $0 inside your Vagrant environment"
  exit 1
fi

# Just for ease of use, let's autoswap to the workspace folder
sed -i -e 's/.*switch to workspace//' ${HOME}/.bash_profile # really hacky idempotency
echo 'cd /vagrant; # switch to workspace' >> ${HOME}/.bash_profile

# We <3 pretty output
sed -i -e 's/.*PS1.*//' ${HOME}/.bash_profile
echo 'export PS1=" \033[1;34mCASEWORK\033[0m \033[1;31m$ \033[0m"' >> ${HOME}/.bash_profile

# Add ./local to PATH
sed -i -e 's/.*add local dir to path//' ${HOME}/.bash_profile
echo 'export PATH=$PATH:/vagrant/local' >> ${HOME}/.bash_profile

[ ! -d /vagrant/logs ] && mkdir -p /vagrant/logs

# Initially we need to install a load of junk thats not provided by landregistry/centos
echo "- - - Installing system dependencies - - -"
sudo yum install -q -y git GitPython PyYAML python-devel python-pip python-virtualenv python-jinja2 supervisor

#install ruby
# system update
yum -y update
yum -y groupinstall "Development Tools"
sudo yum -y install ruby-devel
sudo yum -y install gcc gcc-c++ make flex bison gperf ruby \
  openssl-devel freetype-devel fontconfig-devel libicu-devel sqlite-devel \
  libpng-devel libjpeg-devel

#install phantomjs
echo "- - - installing phantomjs - - -"
  cd ~
  export PHANTOM_JS="phantomjs-1.9.7-linux-x86_64"
  wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  mv $PHANTOM_JS.tar.bz2 /usr/local/share/
  cd /usr/local/share/
  tar xvjf $PHANTOM_JS.tar.bz2
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/share/phantomjs
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/bin/phantomjs

#install bundler
echo "- - - Installing bundler - - -"
gem install bundler --no-rdoc --no-ri

#install postgresql
gem install --no-ri --no-rdoc puppet:3.7.5
puppet module install puppetlabs-apt --version "<2.0.0"
puppet module install puppetlabs-postgresql
puppet apply /vagrant/manifests/postgres.pp
#puppet does not configure headers.  So later installation of psycopg2 fails because libpq-fe.h is not found.
#install postgresql-devel again to fix this (or fix the puppet installation).
sudo yum -y install postgresql-devel
#set known path to pgconfig so psycopg2 can install
if [ -d /usr/pgsql-9.3/bin ]; then
  export PATH=$PATH:/usr/pgsql-9.3/bin
fi

# TEMP
sudo yum install -y gcc -q
sudo systemctl stop firewalld

# Bodge together a supervisor config
sudo systemctl start supervisord >/dev/null 2>&1
sudo systemctl enable supervisord >/dev/null 2>&1
sudo chown -R vagrant:vagrant /etc/supervisord.d/

# Set up applications
echo "- - - Configuring applications - - -"
sudo su vagrant -c /vagrant/local/lr-setup-apps

#install and configure virtualenvwrapper
pip install virtualenvwrapper
source /usr/bin/virtualenvwrapper.sh
echo "source /usr/bin/virtualenvwrapper.sh" >> ${HOME}/.bash_profile
echo "export WORKON_HOME=$WORKON_HOME" >>  ${HOME}/.bash_profile

# Load supervisor config and start applications
echo "- - - Starting services - - -"
sudo supervisorctl reload >/dev/null

yum install -y git

yum install -y java-1.7.0-openjdk-devel

wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo

yum install -y apache-maven

sudo -i -u vagrant source /vagrant/local/provision-adapters.sh

#Install provisions for all applications we've got
provision_scripts=`find /vagrant/apps -regex "/vagrant/apps/.*/provision.sh"`
for script in $provision_scripts
do
	bash $script
done

#add helpful aliases
echo "source /vagrant/local/add-aliases.sh" >> ${HOME}/.bash_profile
