#!/usr/bin/env bash

HOME='/home/vagrant'

# Check yo' privledge
# if [ $(id -u) != 0 ]; then
#   echo "You must be root to run $0"
#   exit 1
# fi

if [[ ! $(id vagrant) ]]; then
  echo "You must run $0 inside your Vagrant environment"
  exit 1
fi

# Just for ease of use, let's autoswap to the workspace folder
sed -i -e 's/.*switch to workspace//' ${HOME}/.bash_profile # really hacky idempotency
echo 'cd /vagrant; # switch to workspace' >> ${HOME}/.bash_profile

# We <3 pretty output
sed -i -e 's/.*PS1.*//' ${HOME}/.bash_profile
echo 'export PS1=" \033[1;34mCASEWORK\033[0m \033[1;31m$ \033[0m"' >> ${HOME}/.bash_profile

# Add ./local to PATH
sed -i -e 's/.*add local dir to path//' ${HOME}/.bash_profile
echo 'export PATH=$PATH:/vagrant/local' >> ${HOME}/.bash_profile

[ ! -d /vagrant/logs ] && mkdir -p /vagrant/logs

# Initially we need to install a load of junk thats not provided by landregistry/centos
echo "- - - Installing system dependencies - - -"
sudo yum install -q -y git GitPython PyYAML python-devel python-pip python-virtualenv python-jinja2 supervisor

#install ruby
# system update
yum -y update
yum -y groupinstall "Development Tools"
sudo yum -y install ruby-devel
sudo yum -y install gcc gcc-c++ make flex bison gperf ruby \
  openssl-devel freetype-devel fontconfig-devel libicu-devel sqlite-devel \
  libpng-devel libjpeg-devel

#install phantomjs
echo "- - - installing phantomjs - - -"
  cd ~
  export PHANTOM_JS="phantomjs-1.9.7-linux-x86_64"
  wget https://bitbucket.org/ariya/phantomjs/downloads/$PHANTOM_JS.tar.bz2
  mv $PHANTOM_JS.tar.bz2 /usr/local/share/
  cd /usr/local/share/
  tar xvjf $PHANTOM_JS.tar.bz2
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/share/phantomjs
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/local/bin/phantomjs
  ln -sf /usr/local/share/$PHANTOM_JS/bin/phantomjs /usr/bin/phantomjs

#install bundler
echo "- - - installing bundler - - -"
gem install bundler

#install postgresql
echo "- - - installing postgresql - - -"
sudo yum install -y http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-1.noarch.rpm
sudo yum install -y postgresql94-server postgresql94-contrib
/usr/pgsql-9.4/bin/postgresql94-setup initdb
systemctl enable postgresql-9.4.service
systemctl start postgresql-9.4.service

# TEMP
sudo yum install -y gcc -q
sudo systemctl stop firewalld

# Bodge together a supervisor config
sudo systemctl start supervisord >/dev/null 2>&1
sudo systemctl enable supervisord >/dev/null 2>&1
sudo chown -R vagrant:vagrant /etc/supervisord.d/

# Set up applications
echo "- - - Configuring applications - - -"
sudo su vagrant -c /vagrant/local/lr-setup-apps

# Load supervisor config and start applications
echo "- - - Starting services - - -"
sudo supervisorctl reload >/dev/null
