---

  applications:
    test-fixtures-api:
      repo: git@git.lr.net:casework/test-fixtures-api.git
      branch: develop
      port: 9090
      run: /bin/sh /vagrant/apps/test-fixtures-api/run.sh
      build: source /vagrant/apps/test-fixtures-api/build.sh
      vars:

    register-adapter:
      repo: git@git.lr.net:casework/register-adapter.git
      branch: develop
      port: 9091
      run: source /vagrant/apps/register-adapter/run.sh
      build: source /vagrant/apps/register-adapter/build.sh
      vars:
