---

  applications:

    cases-api:
      repo: git@github.com:LandRegistry/cases-api.git
      branch: master
      port: 5001
      entrypoint: application:app
      apptype: wsgi
      vars:

    cases-frontend:
      repo: git@github.com:LandRegistry/cases-frontend.git
      branch: master
      port: 5002
      entrypoint: application:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    register-metadata:
      repo: git@github.com:LandRegistry/register-metadata.git
      branch: master
      port: 5003
      entrypoint: application:app
      apptype: wsgi
      vars:

    update-register:
      repo: git@github.com:LandRegistry/update-register.git
      branch: master
      port: 5004
      entrypoint: application.routes:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    titles-api:
      repo: git@github.com:LandRegistry/titles-api.git
      branch: master
      port: 5005
      entrypoint: application:app
      apptype: wsgi
      vars:

    auto-process-charge:
      repo: git@github.com:LandRegistry/auto-process-charge.git
      branch: master
      port: 5006
      entrypoint: application:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    daylist-adapter:
      repo: git@git.lr.net:casework/daylist-adapter.git
      branch: master
      port: 8888
      apptype: torquebox
      vars:

    titles-adapter:
      repo: git@git.lr.net:casework/titles-adapter.git
      branch: master
      port: 8888
      apptype: torquebox
      vars:

    register-adapter:
      repo: git@git.lr.net:casework/register-adapter.git
      branch: master
      port: 8888
      apptype: torquebox
      vars:        

    migrate-metadata:
      repo: git@git.lr.net:casework/migrate-metadata.git
      branch: master
      apptype: jruby script
      vars:

    current-register-api:
      repo: git@github.com:LandRegistry/current-register-api.git
      branch: master
      port: 5007
      entrypoint: application.routes:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    register-publisher:
      repo: git@github.com:LandRegistry/register-publisher.git
      branch: master
      entrypoint: /home/vagrant/.venv/register-publisher/bin/python /vagrant/apps/register-publisher/run.py
      apptype: genericpython
      vars:
        SETTINGS: config.DevelopmentConfig

    current-register-feeder:
      repo: git@github.com:LandRegistry/current-register-feeder.git
      branch: master
      entrypoint: /home/vagrant/.venv/current-register-feeder/bin/python /vagrant/apps/current-register-feeder/run.py
      apptype: genericpython
      vars:
        SETTINGS: config.DevelopmentConfig
