---

  applications:

    cases-api:
      repo: https://github.com/LandRegistry/cases-api.git
      branch: master
      port: 5001
      entrypoint: application:app
      apptype: wsgi
      vars:

    cases-frontend:
      repo: https://github.com/LandRegistry/cases-frontend.git
      branch: master
      port: 5002
      entrypoint: application:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    register-metadata:
      repo: https://github.com/LandRegistry/register-metadata.git
      branch: master
      port: 5003
      entrypoint: application:app
      apptype: wsgi
      vars:

    update-register:
      repo: https://github.com/LandRegistry/update-register.git
      branch: master
      port: 5004
      entrypoint: application.routes:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    titles-api:
      repo: https://github.com/LandRegistry/titles-api.git
      branch: master
      port: 5005
      entrypoint: application:app
      apptype: wsgi
      vars:

    auto-process-charge:
      repo: https://github.com/LandRegistry/auto-process-charge.git
      branch: master
      port: 5006
      entrypoint: application:app
      apptype: wsgi
      vars:
        SETTINGS: config.DevelopmentConfig

    daylist-adapter:
      repo: git@git.lr.net:casework/daylist-adapter.git
      branch: master
      port: 8888
      apptype: torquebox
      vars:

    titles-adapter:
      repo: git@git.lr.net:casework/titles-adapter.git
      branch: master
      port: 8888
      apptype: torquebox
      vars:

    migrate-metadata:
      repo: git@git.lr.net:casework/migrate-metadata.git
      branch: master
      port:
      apptype: jruby
      vars:
