---

  applications:
    test-fixtures-api:
      repo: git@git.lr.net:casework/test-fixtures-api.git
      branch: develop
      port: 9090
      run: /bin/sh /vagrant/apps/test-fixtures-api/run.sh
      build: source /vagrant/apps/test-fixtures-api/build.sh
      language: gradle
      vars:

    register-adapter:
      repo: git@git.lr.net:casework/register-adapter.git
      branch: develop
      port: 9091
      run: /bin/sh /vagrant/apps/register-adapter/run.sh
      build: source /vagrant/apps/register-adapter/build.sh
      language: gradle
      vars:

    acceptance-tests:
      repo: git@git.lr.net:casework/acceptance-tests.git
      branch: develop
      language: ruby
      vars:

    migrate_metadata:
      repo: git@git.lr.net:casework/migrate_metadata.git
      branch: develop
      language: gradle
      vars:

    process-digital-mortgage:
      repo: git@git.lr.net:casework/process-digital-mortgage.git
      branch: develop
      port: 5000
      run: /bin/sh /vagrant/apps/process-digital-mortgage/run.sh
      build: /bin/sh /vagrant/apps/process-digital-mortgage/upgrade.sh
      language: python
      vars:

    deed_api_stub:
      repo: git@git.lr.net:casework/deed-api-stub.git
      branch: develop
      port: 5006
      run: /bin/sh /vagrant/apps/deed-api-stub/run.sh
      language: python
      vars:

    title-adapter-api:
      repo: git@192.168.249.38:common/title-adapter-api.git
      branch: develop
      port: 9092
      run: /bin/sh /vagrant/apps/title-adapter-api/run.sh
      build: source /vagrant/apps/title-adapter-api/build.sh
      language: gradle
      vars:


