---

  applications:

    cases-api:
      repo: https://github.com/LandRegistry/cases-api.git
      branch: master
      port: 5001
      entrypoint: application:app
      vars:

    cases-frontend:
      repo: https://github.com/LandRegistry/cases-frontend.git
      branch: master
      port: 5002
      entrypoint: application:app
      vars:
        SETTINGS: config.DevelopmentConfig

    register-metadata:
      repo: https://github.com/LandRegistry/register-metadata.git
      branch: master
      port: 5003
      entrypoint: application:app
      vars:

    update-register:
      repo: https://github.com/LandRegistry/update-register.git
      branch: master
      port: 5004
      entrypoint: application:app
      vars:

    titles-api:
      repo: https://github.com/LandRegistry/titles-api.git
      branch: master
      port: 5005
      entrypoint: application:app
      vars:

    auto-process-charge:
      repo: https://github.com/LandRegistry/auto-process-charge.git
      branch: master
      port: 5006
      entrypoint: application:app
      vars: