---

  applications:

    cases-api:
      repo: https://github.com/LandRegistry/cases-api.git
      branch: master
      port: 5001
      entrypoint: application.cases-api:app
      vars:

    cases-frontend:
      repo: https://github.com/LandRegistry/cases-frontend.git
      branch: master
      port: 5002
      entrypoint: application.cases-frontend:app
      vars:

    casework-frontend:
      repo: https://github.com/LandRegistry/casework-frontend.git
      branch: master
      port: 5003
      entrypoint: application.casework-frontend:app
      vars:
