---

  applications:

    cases-api:
      repo: https://github.com/LandRegistry/cases-api.git
      branch: master
      port: 5001
      entrypoint: application:app
      vars:

    cases-frontend:
      repo: https://github.com/LandRegistry/cases-frontend.git
      branch: master
      port: 5002
      entrypoint: application:app
      vars:
        SETTINGS: config.DevelopmentConfig

    casework-frontend:
      repo: https://github.com/LandRegistry/casework-frontend.git
      branch: master
      port: 5003
      entrypoint: application:app
      vars:
